//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnTopReplica {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OnTopReplica.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   &amp;Cancel과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ButtonCancel {
            get {
                return ResourceManager.GetString("ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   마우스로 영역을 선택해 주세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DrawRegions {
            get {
                return ResourceManager.GetString("DrawRegions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   세부 사항과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ErrorDetailButton {
            get {
                return ResourceManager.GetString("ErrorDetailButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Windows Aero에 대한 세부 정보과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ErrorDetailsAero {
            get {
                return ResourceManager.GetString("ErrorDetailsAero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Windows Aero는 Windows Vista Home Premium 이상에서만 사용할 수 있습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ErrorDetailsAeroInfo {
            get {
                return ResourceManager.GetString("ErrorDetailsAeroInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;데스크톱 구성&apos;이 활성화되지 않았습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ErrorDwmOff {
            get {
                return ResourceManager.GetString("ErrorDwmOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Windows에서 사용하는 테마로 &apos;Windows Aero&apos;를 선택하여 바탕 화면 구성을 활성화하십시오.
        ///
        ///이렇게 하려면 바탕 화면을 마우스 오른쪽 단추로 클릭하고 개인 설정을 클릭하십시오.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ErrorDwmOffContent {
            get {
                return ResourceManager.GetString("ErrorDwmOffContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   오류내역과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ErrorGenericInfoButton {
            get {
                return ResourceManager.GetString("ErrorGenericInfoButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   오류:과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ErrorGenericInfoText {
            get {
                return ResourceManager.GetString("ErrorGenericInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   선택한 창이 닫혔거나 더 이상 유효하지 않은 것으로 나타납니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ErrorGenericThumbnailHandleError {
            get {
                return ResourceManager.GetString("ErrorGenericThumbnailHandleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   오류과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ErrorGenericTitle {
            get {
                return ResourceManager.GetString("ErrorGenericTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;데스크톱 구성&apos;은 운영 체제에서 지원되지 않습니다.
        ///이 응용 프로그램은 Windows Vista Home Premium 이상에서 실행하십시오.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ErrorNoDwm {
            get {
                return ResourceManager.GetString("ErrorNoDwm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   지원되지 않는 데스크톱 구성과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ErrorNoDwmTitle {
            get {
                return ResourceManager.GetString("ErrorNoDwmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   미리 보기가 로드되지 않음.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ErrorNoThumbnail {
            get {
                return ResourceManager.GetString("ErrorNoThumbnail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   미리 보기를 만들 수 없음과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ErrorUnableToCreateThumbnail {
            get {
                return ResourceManager.GetString("ErrorUnableToCreateThumbnail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   윈도우를 맞출 수 없음.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ErrorUnableToFit {
            get {
                return ResourceManager.GetString("ErrorUnableToFit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   모드과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FullscreenMode {
            get {
                return ResourceManager.GetString("FullscreenMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   항상 맨 위에 있음과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FullscreenModeAlwaysOnTop {
            get {
                return ResourceManager.GetString("FullscreenModeAlwaysOnTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   항상 맨 위에 있도록 합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FullscreenModeAlwaysOnTopTT {
            get {
                return ResourceManager.GetString("FullscreenModeAlwaysOnTopTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   클릭 통과과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FullscreenModeClickThrough {
            get {
                return ResourceManager.GetString("FullscreenModeClickThrough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   클릭이 아래 창으로 전달되는 투명한 오버레이처럼 동작합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FullscreenModeClickThroughTT {
            get {
                return ResourceManager.GetString("FullscreenModeClickThroughTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   표준과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FullscreenModeNormal {
            get {
                return ResourceManager.GetString("FullscreenModeNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   위에 다른 창을 가져올 수 있습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FullscreenModeNormalTT {
            get {
                return ResourceManager.GetString("FullscreenModeNormalTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   전체 화면과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FullscreenTitle {
            get {
                return ResourceManager.GetString("FullscreenTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   사용 안함과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GroupSwitchModeDisableButton {
            get {
                return ResourceManager.GetString("GroupSwitchModeDisableButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   그룹 모드 사용과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GroupSwitchModeEnableButton {
            get {
                return ResourceManager.GetString("GroupSwitchModeEnableButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   사용할 여러 창을 선택해 주세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GroupSwitchModeStatusDisabled {
            get {
                return ResourceManager.GetString("GroupSwitchModeStatusDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   그룹 스위치 모드가 활성화됩니다과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GroupSwitchModeStatusEnabled {
            get {
                return ResourceManager.GetString("GroupSwitchModeStatusEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   그룹 스위치 모드:과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GroupSwitchModeTitle {
            get {
                return ResourceManager.GetString("GroupSwitchModeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   윈도우과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GroupSwitchModeWindows {
            get {
                return ResourceManager.GetString("GroupSwitchModeWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &quot;클릭 전달&quot;을 사용하시겠습니까?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string InfoClickForwarding {
            get {
                return ResourceManager.GetString("InfoClickForwarding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   이 모드가 활성화되면 복제 중인 창으로 마우스 왼쪽 클릭을 모두 전달합니다(이렇게 하면 복제된 창에서 활성화할 필요 없이 기본 마우스 작업을 수행할 수 있습니다).
        ///
        ///이 모드를 종료하려면 ESC를 누르십시오.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string InfoClickForwardingContent {
            get {
                return ResourceManager.GetString("InfoClickForwardingContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   클릭 전달과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string InfoClickForwardingTitle {
            get {
                return ResourceManager.GetString("InfoClickForwardingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   클릭 전달 모드를 사용 하시겠습니까?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string InfoClickThrough {
            get {
                return ResourceManager.GetString("InfoClickThrough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   클릭 연결은 크기 조정 하위 메뉴에서 활성화되어 있고 창이 반투명 한 경우에만 작동합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string InfoClickThroughDetails {
            get {
                return ResourceManager.GetString("InfoClickThroughDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   이 모드에서 전체 화면 창은 부분적으로 투명한 오버레이로 작동하여 그 뒤에있는 다른 창을 클릭 할 수 있습니다.
        ///
        ///언제든지 일반 모드로 돌아가려면 작업 표시 줄 (또는 트레이 아이콘)을 클릭하여 활성화하십시오.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string InfoClickThroughInformation {
            get {
                return ResourceManager.GetString("InfoClickThroughInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   아니요 괜찮습니다.
        ///나중에 클릭 연결을 활성화 할 수 있습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string InfoClickThroughNo {
            get {
                return ResourceManager.GetString("InfoClickThroughNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   클릭 통과 사용과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string InfoClickThroughOk {
            get {
                return ResourceManager.GetString("InfoClickThroughOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   클릭 통과 모드과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string InfoClickThroughTitle {
            get {
                return ResourceManager.GetString("InfoClickThroughTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   추가 기능과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MenuAdvanced {
            get {
                return ResourceManager.GetString("MenuAdvanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   창 테두리 표시과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MenuChrome {
            get {
                return ResourceManager.GetString("MenuChrome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   창 테두리의 표시를 전환합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MenuChromeTT {
            get {
                return ResourceManager.GetString("MenuChromeTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   클릭 전달 사용과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MenuClickForwarding {
            get {
                return ResourceManager.GetString("MenuClickForwarding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   복제된 창으로 &quot;클릭 전달&quot;을 사용 가능으로 설정하십시오.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MenuClickForwardingTT {
            get {
                return ResourceManager.GetString("MenuClickForwardingTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   클릭 통과 사용과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MenuClickThrough {
            get {
                return ResourceManager.GetString("MenuClickThrough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   클릭이 아래 창으로 전달되는 투명한 오버레이처럼 동작합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MenuClickThroughTT {
            get {
                return ResourceManager.GetString("MenuClickThroughTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   닫기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MenuClose {
            get {
                return ResourceManager.GetString("MenuClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   멀티 윈도우를 닫습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MenuCloseTT {
            get {
                return ResourceManager.GetString("MenuCloseTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   2:1 2배과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MenuFitDouble {
            get {
                return ResourceManager.GetString("MenuFitDouble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   전체 화면과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MenuFitFullscreen {
            get {
                return ResourceManager.GetString("MenuFitFullscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1:2 절반과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MenuFitHalf {
            get {
                return ResourceManager.GetString("MenuFitHalf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1:1 같은 크기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MenuFitOriginal {
            get {
                return ResourceManager.GetString("MenuFitOriginal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   4:1 4분의 1과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MenuFitQuarter {
            get {
                return ResourceManager.GetString("MenuFitQuarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   그룹 스위치 모드과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MenuGroupSwitch {
            get {
                return ResourceManager.GetString("MenuGroupSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   사용자 정의 그룹에서 창을 자동으로 복제하여 가장 최근에 활성화되지 않은 영역으로 전환합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MenuGroupSwitchTT {
            get {
                return ResourceManager.GetString("MenuGroupSwitchTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   100% (불투명)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MenuOp100 {
            get {
                return ResourceManager.GetString("MenuOp100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   완전히 불투명하게 설정합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MenuOp100TT {
            get {
                return ResourceManager.GetString("MenuOp100TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   25%과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MenuOp25 {
            get {
                return ResourceManager.GetString("MenuOp25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   25% 불투명도로 설정합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MenuOp25TT {
            get {
                return ResourceManager.GetString("MenuOp25TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   50%과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MenuOp50 {
            get {
                return ResourceManager.GetString("MenuOp50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   50% 불투명도로 설정합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MenuOp50TT {
            get {
                return ResourceManager.GetString("MenuOp50TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   75%과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MenuOp75 {
            get {
                return ResourceManager.GetString("MenuOp75", resourceCulture);
            }
        }
        
        /// <summary>
        ///   75% 불투명도로 설정합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MenuOp75TT {
            get {
                return ResourceManager.GetString("MenuOp75TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   불투명도과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MenuOpacity {
            get {
                return ResourceManager.GetString("MenuOpacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   열기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MenuOpen {
            get {
                return ResourceManager.GetString("MenuOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   멀티 윈도우를 표시합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MenuOpenTT {
            get {
                return ResourceManager.GetString("MenuOpenTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   왼쪽 하단과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MenuPosBottomLeft {
            get {
                return ResourceManager.GetString("MenuPosBottomLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   오른쪽 하단과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MenuPosBottomRight {
            get {
                return ResourceManager.GetString("MenuPosBottomRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   중앙과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MenuPosCenter {
            get {
                return ResourceManager.GetString("MenuPosCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   사용 안함과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MenuPosDisabled {
            get {
                return ResourceManager.GetString("MenuPosDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   위치 잠금과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MenuPosition {
            get {
                return ResourceManager.GetString("MenuPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   현재 화면에 멀티 윈도우 자동 배치과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MenuPositionTT {
            get {
                return ResourceManager.GetString("MenuPositionTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   왼쪽 상단과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MenuPosTopLeft {
            get {
                return ResourceManager.GetString("MenuPosTopLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   오른쪽 상단과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MenuPosTopRight {
            get {
                return ResourceManager.GetString("MenuPosTopRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   전체 화면 모드 종료과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MenuQuitFullscreen {
            get {
                return ResourceManager.GetString("MenuQuitFullscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   마지막 위치 및 크기 호출과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MenuRecall {
            get {
                return ResourceManager.GetString("MenuRecall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   마지막 위치와 크기를 저장하고 재시작할 때 이를 사용할지 선택해 주세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MenuRecallTT {
            get {
                return ResourceManager.GetString("MenuRecallTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   최소화과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MenuReduce {
            get {
                return ResourceManager.GetString("MenuReduce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   작업 표시줄에 최소화과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MenuReduceTT {
            get {
                return ResourceManager.GetString("MenuReduceTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   돋보기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MenuRegion {
            get {
                return ResourceManager.GetString("MenuRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   화면의 일부 또는 전부를 확대하면 단어와 이미지를 더 잘 볼 수 있습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MenuRegionTT {
            get {
                return ResourceManager.GetString("MenuRegionTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   창 초기화과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MenuReset {
            get {
                return ResourceManager.GetString("MenuReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   설정 및 기본창을 초기화합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MenuResetTT {
            get {
                return ResourceManager.GetString("MenuResetTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   크기 조정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MenuResize {
            get {
                return ResourceManager.GetString("MenuResize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   마지막으로 복제된 창 복원과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MenuRestoreLast {
            get {
                return ResourceManager.GetString("MenuRestoreLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   활성화되면 시작시 마지막으로 복제 된 창을 복원합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MenuRestoreLastTT {
            get {
                return ResourceManager.GetString("MenuRestoreLastTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   설정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MenuSettings {
            get {
                return ResourceManager.GetString("MenuSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   설정창을 표시합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MenuSettingsTT {
            get {
                return ResourceManager.GetString("MenuSettingsTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   창으로 전환과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MenuSwitch {
            get {
                return ResourceManager.GetString("MenuSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   현재 보이는 창으로 전환하고 숨깁니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MenuSwitchTT {
            get {
                return ResourceManager.GetString("MenuSwitchTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   창 선택과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MenuWindows {
            get {
                return ResourceManager.GetString("MenuWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   -없음-과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MenuWindowsNone {
            get {
                return ResourceManager.GetString("MenuWindowsNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   멀티 윈도우로 선택할 수 있는 창 목록을 표시합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MenuWindowsTT {
            get {
                return ResourceManager.GetString("MenuWindowsTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   -선택-과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MenuWindowsWholeRegion {
            get {
                return ResourceManager.GetString("MenuWindowsWholeRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   아래과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string RegionsBottom {
            get {
                return ResourceManager.GetString("RegionsBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   현재 크기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string RegionsCurrentRegion {
            get {
                return ResourceManager.GetString("RegionsCurrentRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   삭제과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string RegionsDeleteButton {
            get {
                return ResourceManager.GetString("RegionsDeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   저장과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string RegionsDoneButton {
            get {
                return ResourceManager.GetString("RegionsDoneButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   높이과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string RegionsHeight {
            get {
                return ResourceManager.GetString("RegionsHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   왼쪽과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string RegionsLeft {
            get {
                return ResourceManager.GetString("RegionsLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   초기화과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string RegionsResetButton {
            get {
                return ResourceManager.GetString("RegionsResetButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   오른쪽과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string RegionsRight {
            get {
                return ResourceManager.GetString("RegionsRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   저장과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string RegionsSaveButton {
            get {
                return ResourceManager.GetString("RegionsSaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   저장된 영역입니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string RegionsStoredRegions {
            get {
                return ResourceManager.GetString("RegionsStoredRegions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   영역은 다음과 같습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string RegionsTitle {
            get {
                return ResourceManager.GetString("RegionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   위과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string RegionsTop {
            get {
                return ResourceManager.GetString("RegionsTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   너비과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string RegionsWidth {
            get {
                return ResourceManager.GetString("RegionsWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   X과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string RegionsX {
            get {
                return ResourceManager.GetString("RegionsX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Y과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string RegionsY {
            get {
                return ResourceManager.GetString("RegionsY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   여기를 마우스 오른쪽 단추로 클릭과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string RightClick {
            get {
                return ResourceManager.GetString("RightClick", resourceCulture);
            }
        }
    }
}
